In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [3]:
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [4]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [5]:
arr1^arr2

array([ 7,  5, 11, 13, 15])

In [6]:
arr1|arr2

array([ 7,  7, 11, 13, 15])

In [7]:
arr1&arr2

array([0, 2, 0, 0, 0])

In [8]:
arr1**arr2

array([      1,     128,    6561,  262144, 9765625])

In [20]:
arr1=np.arange(1,7).reshape(3,2)
arr2=np.arange(11,17).reshape(3,2)

In [21]:
arr1*arr2

array([[11, 24],
       [39, 56],
       [75, 96]])

In [11]:
arr1,arr2

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[11, 12],
        [13, 14],
        [15, 16]]))

In [12]:
arr1%arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
arr1/arr2

array([[0.09090909, 0.16666667],
       [0.23076923, 0.28571429],
       [0.33333333, 0.375     ]])

In [14]:
arr1**arr2

array([[            1,          4096],
       [      1594323,     268435456],
       [  30517578125, 2821109907456]])

In [15]:
arr1&arr2

array([[1, 0],
       [1, 4],
       [5, 0]])

In [19]:
arr1@arr2

array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]])

In [23]:
np.vstack((arr1,arr2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [13, 14],
       [15, 16]])

In [24]:
np.hstack((arr1,arr2))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16]])

In [26]:
np.column_stack((arr1,arr2))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16]])

In [27]:
np.row_stack((arr1,arr2))

/var/folders/6l/65cwxjvx5zg5ssk6xb0pr7kr0000gn/T/ipykernel_5911/3845226977.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((arr1,arr2))


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [13, 14],
       [15, 16]])

In [29]:
arr3=np.arange(1,17).reshape(4,4)

In [30]:
np.vsplit(arr3,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [32]:
np.hsplit(arr3,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]