In [4]:
import numpy as np

In [5]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [6]:
s.sum()

np.int64(405)

In [7]:
np.sum(s,axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [8]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [9]:
(np.sum(s,axis=1)==np.sum(s,axis=0))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [10]:
print(s)
for i in range(0,3):
    for j in range(0,3):
        if ((s[i*3:i*3+3,j*3:j*3+3]).sum())==45:
            continue
        else:
            print("Not valid")
            break 

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [11]:
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [12]:
data.shape

(5, 3)

In [13]:
data[0:,0].mean()

np.float64(18.4)

In [19]:
data[0:,1]+=5

In [20]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [22]:
a=data[0:,0]<19

In [24]:
np.mean(data,axis=0)

array([18.4, 86.6, 83.2])

In [33]:
a=data[0:,1:]>=80

array([[ True, False],
       [ True,  True],
       [ True,  True],
       [False, False],
       [ True,  True]])

In [36]:
data[0:,2][data[0:,2]<75]=0

In [37]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])