In [1]:
import numpy as np

In [2]:
arr=np.arange(11,21)

In [3]:
arr[1]

np.int64(12)

In [4]:
print(arr[2])

13


In [5]:
arr[2:6]

array([13, 14, 15, 16])

In [9]:
arr=np.arange(1,31).reshape(6,5)

In [10]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[2]

array([11, 12, 13, 14, 15])

In [14]:
arr[2,3]

np.int64(14)

In [13]:
arr[2,4]

np.int64(15)

In [15]:
arr[(0,1),(1,2)]

array([2, 8])

In [16]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [17]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [20]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [21]:
arr=np.arange(1,11)

In [22]:
bool_ind=arr%2==0

In [23]:
bool_ind

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [28]:
arr[bool_ind]

array([ 2,  4,  6,  8, 10])

In [25]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])