In [51]:
import numpy as np 

In [ ]:
arr =np.array([1,2,3,4])

In [ ]:
print(arr)

In [ ]:
arr

In [ ]:
arr= np.array([1,2,3,'Hi',4.6])

In [ ]:
arr

In [ ]:
l=[[1,2,3]]*3
l

In [ ]:
arr=np.array(l)

In [ ]:
arr

In [ ]:
arr=np.arange(1,11,2)

In [ ]:
arr*2

In [ ]:
arr=np.zeros(6)

In [ ]:
arr

In [ ]:
arr=np.zeros((2,4))
arr

In [ ]:
arr=np.ones(3)

In [ ]:
arr

In [ ]:
np.linspace(1,10)

In [ ]:
np.linspace(1,2,3)

In [ ]:
np.random.rand(10)

In [ ]:
np.random.randn(5)

In [ ]:
np.random.randint(1,6,4)

In [ ]:

Array attributes


In [ ]:
arr.shape

In [ ]:
arr

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr.shape

In [ ]:
arr.size

In [ ]:
arr.dtype

In [ ]:
arr.min()

In [ ]:
arr.max()

In [ ]:
arr

In [ ]:
arr.min()

In [ ]:
arr.mean()

In [ ]:
arr.sum()

In [ ]:
np.sum(arr,axis=1)

In [ ]:
np.sum(arr,axis=0)

In [ ]:
arr.std()

In [54]:
arr.argmax()

np.int64(29)

In [55]:
arr.argmin()

np.int64(0)

In [57]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [58]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [59]:
arr.resize()

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [62]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])